from talon import Module
mod = Module()
mod.mode("french")
mod.mode("german")
mod.mode("portuguese")
mod.mode("russian")
mod.mode("spanish")
mod.mode("swedish")
mod.mode("english")
mod.mode("japanese")
mod.mode("dutch")
mod.mode("mandarin")
mod.mode("romanian")
